site_name: TAG Heuer Replica
site_description: Explore luxury-inspired timepieces with precision and design excellence.
site_author: TAG Heuer Replica Team
repo_url: https://github.com/lethanhdung18070-sketch/TAG-Heuer-Replica
docs_dir: docs
theme:
  name: readthedocs
